name: Deploy to Amazon EC2

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy Nausicaa
    runs-on: ubuntu-latest

    steps:    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

#    - name: Set up Java paths
      # Since Java is already installed on the custom AMI, no need to install it again.
#      run: |
#        export JAVA_HOME=/usr/lib/jvm/java-21-amazon-corretto
#        export PATH=$JAVA_HOME/bin:$PATH
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Copy artifact to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: 'target/Global-Green-Initiative-0.0.1-SNAPSHOT.jar'
        target: '~/ggi/Global-Green-Initiative-0.0.1-SNAPSHOT.jar'

    - name: SSH into EC2 and restart application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo systemctl restart Global-Green-Initiative-0.0.1-SNAPSHOT.jar.service
