name: Java CI with Maven

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - id: honeycomb-setup-recording
        uses: honeycombio/gha-buildevents@v1
        with:
          # Required: a Honeycomb API key - needed to send traces.
          #   must be set in your GitHub repository under Settings > Secrets > Actions
          apikey: ${{ secrets.BUILDEVENT_APIKEY }}

          # Required: the Honeycomb dataset to send traces to
          dataset: buildevents

          # Required: the job status, this will be used in the post section and sent
          #   as status of the trace. Must always be ${{ job.status }}.
          job-status: ${{ job.status }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -f Global-Green-Initiative/pom.xml clean install
        
      - name: Install Snyk CLI
        run: |
         curl -L https://npmjs.org/install.sh | sudo sh
          sudo npm install -g snyk

      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_API_TOKEN }}
      
      - name: Run Snyk Test
        run: snyk test --json > snyk-test-results.json || true || snyk test --print-deps

      - name: Display Test Results
        run: cat snyk-test-results.json
