name: Selenium with TestNG - CI
 
on:
  push:
    branches: [ "main" ]

 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Check out UI repo
      uses: actions/checkout@master
      with:
          repository: PGDip-DevOps-Group2/Global-Green-Initiative-UiAutomation
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
     
    - uses: browser-actions/setup-chrome@latest
    - run: chrome --version
     
    - name: Build with Maven
      run: |
            ls
            cd GlobalGreenInitiative-UIAuto
            ls
            ls
            mvn clean install
            mvn clean test